# Generated by Django 4.1.2 on 2022-12-17 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Courses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Courses_name", models.CharField(max_length=200)),
                ("Courses_fees", models.CharField(max_length=200)),
                ("Courses_duration", models.CharField(max_length=200)),
                ("Courses_textbox", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("email", models.CharField(max_length=200)),
                ("password", models.CharField(blank=True, max_length=500, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=200)),
                ("student_email", models.CharField(max_length=200)),
                ("student_mobile", models.IntegerField()),
                ("student_college", models.CharField(max_length=200)),
                ("student_degree", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "Courses_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management.courses",
                    ),
                ),
            ],
        ),
    ]
